from __future__ import annotations

from typing import Protocol, Any

from app.domain.models import MutationResult, ProductState, Promotion


class PromotionRepository(Protocol):
    def list_promotions(self) -> list[Promotion]: ...
    def list_candidates(self, action_id: str, **kwargs) -> dict[str, Any]: ...
    def list_participants(self, action_id: str, **kwargs) -> list[ProductState]: ...
    def read_participants(self, action_id: str, **kwargs) -> list[ProductState]: ...
    def update_products(self, action_id: str, products: list[dict[str, Any]]) -> MutationResult: ...
